### ISSUE TITLE
[Bug?] Should the return type be AsyncIterator instead of AsyncGenerator

### ISSUE THREAD

**Issue by uetchy** [MadProbe/iterator-helpers-polyfill#10]
<img width="667" alt="Screen Shot 2022-04-24 at 14 02 35" src="https://user-images.githubusercontent.com/431808/164957427-4fd8c292-93e7-41d9-a8e8-100c136b1638.png">

Otherwise, we couldn't get the correct type reference when chaining helper functions, since those functions don't exist on `AsyncGenerator`.

# Current behaviour

In a Node.js module:
<img width="427" alt="Screen Shot 2022-04-24 at 14 09 38" src="https://user-images.githubusercontent.com/431808/164957625-78499d2b-c845-41dd-b892-866dde7e4270.png">

A caller in another module:
<img width="719" alt="Screen Shot 2022-04-24 at 14 10 03" src="https://user-images.githubusercontent.com/431808/164957627-e857b598-3566-4062-97ed-3fcf55fd5f81.png">

**Comment by MadProbe** [comment]
I don't think this is a bug because:
1. AsyncGenerator interface extends the AsyncIterator interface
2. In the actual implementation async generators are used but not object implementing async iterator interface.
3. [Proposal specification](https://tc39.es/proposal-iterator-helpers/#sec-iterator-helper-objects) mandates use of sync and async generators.

I think you need to triple-slash reference the typings of polyfill or simply import polyfill's module to fix your issue.
